-- Django utilizes models to auto-generate SQL queries.
-- These SQL lines are obtained by:
-- First, $ python manage.py makemigrations <app_name>
-- -- <app_name> is one of {adminstaff, classes, club, equipment, members, rooms, trainers}
-- Then, $ python manage.py sqlmigrate <app_name> <migration_number>

-- User can either use:
-- 1.
-- $ python manage.py makemigrations
-- $ python manage.py migrate to finish the table creation
-- or
-- 2. run query with DML_Django.sql in PGadmin

--
-- Create model Club
--
CREATE TABLE "club_user" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "password" varchar(128) NOT NULL, "last_login" timestamp with time zone NULL, "is_superuser" boolean NOT NULL, "email" varchar(254) NOT NULL UNIQUE, "first_name" varchar(255) NOT NULL, "last_name" varchar(255) NOT NULL, "is_member" boolean NOT NULL, "is_trainer" boolean NOT NULL, "is_staff" boolean NOT NULL);
CREATE TABLE "club_user_groups" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "group_id" integer NOT NULL);
CREATE TABLE "club_user_user_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "permission_id" integer NOT NULL);
CREATE INDEX "club_user_email_39c1c2b1_like" ON "club_user" ("email" varchar_pattern_ops);
ALTER TABLE "club_user_groups" ADD CONSTRAINT "club_user_groups_user_id_group_id_c4b869a8_uniq" UNIQUE ("user_id", "group_id");
ALTER TABLE "club_user_groups" ADD CONSTRAINT "club_user_groups_user_id_e01d0f44_fk_club_user_id" FOREIGN KEY ("user_id") REFERENCES "club_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "club_user_groups" ADD CONSTRAINT "club_user_groups_group_id_7874c7f7_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "club_user_groups_user_id_e01d0f44" ON "club_user_groups" ("user_id");
CREATE INDEX "club_user_groups_group_id_7874c7f7" ON "club_user_groups" ("group_id");
ALTER TABLE "club_user_user_permissions" ADD CONSTRAINT "club_user_user_permissions_user_id_permission_id_fbed0a7c_uniq" UNIQUE ("user_id", "permission_id");
ALTER TABLE "club_user_user_permissions" ADD CONSTRAINT "club_user_user_permissions_user_id_48673e1a_fk_club_user_id" FOREIGN KEY ("user_id") REFERENCES "club_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "club_user_user_permissions" ADD CONSTRAINT "club_user_user_permi_permission_id_527b28bc_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "club_user_user_permissions_user_id_48673e1a" ON "club_user_user_permissions" ("user_id");
CREATE INDEX "club_user_user_permissions_permission_id_527b28bc" ON "club_user_user_permissions" ("permission_id");

--
-- Create model AdminStaff
--
CREATE TABLE "adminstaff_adminstaff" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL UNIQUE);
ALTER TABLE "adminstaff_adminstaff" ADD CONSTRAINT "adminstaff_adminstaff_user_id_51921762_fk_club_user_id" FOREIGN KEY ("user_id") REFERENCES "club_user" ("id") DEFERRABLE INITIALLY DEFERRED;

--
-- Create model Trainer
--
CREATE TABLE "trainers_trainer" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "exercise_type" varchar(50) NOT NULL, "user_id" bigint NOT NULL UNIQUE);

--
-- Create model Trainer_Availability
--
CREATE TABLE "trainers_trainer_availability" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "date" date NOT NULL, "status" varchar(50) NOT NULL, "trainer_id" bigint NOT NULL);
ALTER TABLE "trainers_trainer" ADD CONSTRAINT "trainers_trainer_user_id_cb9b2550_fk_club_user_id" FOREIGN KEY ("user_id") REFERENCES "club_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "trainers_trainer_availability" ADD CONSTRAINT "trainers_trainer_availability_trainer_id_date_d8af37f9_uniq" UNIQUE ("trainer_id", "date");
ALTER TABLE "trainers_trainer_availability" ADD CONSTRAINT "trainers_trainer_ava_trainer_id_d583f8dd_fk_trainers_" FOREIGN KEY ("trainer_id") REFERENCES "trainers_trainer" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "trainers_trainer_availability_trainer_id_d583f8dd" ON "trainers_trainer_availability" ("trainer_id");

--
-- Create model Member
--
CREATE TABLE "members_member" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL UNIQUE);
--
-- Create model Health_Metrics
--
CREATE TABLE "members_health_metrics" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "height" integer NOT NULL, "weight" numeric(5, 2) NOT NULL, "bfp" numeric(5, 2) NOT NULL, "date" date NOT NULL, "member_id" bigint NOT NULL);
--
-- Create model Fitness_Goals
--
CREATE TABLE "members_fitness_goals" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "exercise_type" varchar(50) NOT NULL, "duration" integer NOT NULL, "member_id" bigint NOT NULL);
--
-- Create model Exercise
--
CREATE TABLE "members_exercise" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "exercise_type" varchar(50) NOT NULL, "duration" integer NOT NULL, "date" date NOT NULL, "member_id" bigint NOT NULL);
--
-- Create model Payment
--
CREATE TABLE "members_payment" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "payment_type" varchar(50) NOT NULL, "amount" numeric(10, 2) NOT NULL, "date" date NOT NULL, "status" varchar(50) NOT NULL, "member_id" bigint NOT NULL);
ALTER TABLE "members_member" ADD CONSTRAINT "members_member_user_id_5b73e2f8_fk_club_user_id" FOREIGN KEY ("user_id") REFERENCES "club_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "members_health_metrics" ADD CONSTRAINT "members_health_metrics_member_id_d9ca8487_fk_members_member_id" FOREIGN KEY ("member_id") REFERENCES "members_member" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "members_health_metrics_member_id_d9ca8487" ON "members_health_metrics" ("member_id");
ALTER TABLE "members_fitness_goals" ADD CONSTRAINT "members_fitness_goals_member_id_52af51c8_fk_members_member_id" FOREIGN KEY ("member_id") REFERENCES "members_member" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "members_fitness_goals_member_id_52af51c8" ON "members_fitness_goals" ("member_id");
ALTER TABLE "members_exercise" ADD CONSTRAINT "members_exercise_member_id_094f8507_fk_members_member_id" FOREIGN KEY ("member_id") REFERENCES "members_member" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "members_exercise_member_id_094f8507" ON "members_exercise" ("member_id");
ALTER TABLE "members_payment" ADD CONSTRAINT "members_payment_member_id_1617e0de_fk_members_member_id" FOREIGN KEY ("member_id") REFERENCES "members_member" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "members_payment_member_id_1617e0de" ON "members_payment" ("member_id");

--
-- Create model Room
--
CREATE TABLE "rooms_room" ("room_id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "room_type" varchar(50) NOT NULL, "status" varchar(50) NOT NULL);

--
-- Create model Equipment
--
CREATE TABLE "equipment_equipment" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "equipment_type" varchar(50) NOT NULL, "status" varchar(50) NOT NULL);

--
-- Create model Class
--
CREATE TABLE "classes_class" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "duration" integer NOT NULL, "date" date NOT NULL, "member_id" bigint NOT NULL, "room_id" integer NULL, "trainer_id" bigint NOT NULL);
ALTER TABLE "classes_class" ADD CONSTRAINT "classes_class_member_id_18c4b053_fk_members_member_id" FOREIGN KEY ("member_id") REFERENCES "members_member" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "classes_class" ADD CONSTRAINT "classes_class_room_id_64670992_fk_rooms_room_room_id" FOREIGN KEY ("room_id") REFERENCES "rooms_room" ("room_id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "classes_class" ADD CONSTRAINT "classes_class_trainer_id_d08eccfd_fk_trainers_trainer_id" FOREIGN KEY ("trainer_id") REFERENCES "trainers_trainer" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "classes_class_member_id_18c4b053" ON "classes_class" ("member_id");
CREATE INDEX "classes_class_room_id_64670992" ON "classes_class" ("room_id");
CREATE INDEX "classes_class_trainer_id_d08eccfd" ON "classes_class" ("trainer_id");