# Generated by Django 5.0.3 on 2024-03-30 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainerAvailability',
            new_name='Trainer_Availability',
        ),
    ]
