# Generated by Django 5.0.3 on 2024-03-31 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='last_name',
        ),
    ]
